### ISSUE TITLE
A MIDI plugin in Live?

### ISSUE THREAD

**Issue by paulkernfeld** [RustAudio/vst-rs#118]
Is it possible to use this to make a MIDI plugin that can be used in Ableton Live? I have tried several combinations of settings but I haven't yet hit on something that works. If someone can point me in the general direction I will be happy to do the legwork myself. So far, I have tried the `fwd_midi` example and executed the steps [here](https://help.ableton.com/hc/en-us/articles/209070189-Accessing-the-MIDI-output-of-a-VST-plug-in), but I didn't get any MIDI output. One thing that seemed weird was that Live drops it into the spot for an audio plugin (to the right of the instrument in the UI) rather than the spot for a MIDI plugin (to the left of the instrument).

**Comment by Boscop** [comment]
Yes, it should work. I haven't used Ableton since v9 but I've been writing several midi to midi VSTs and they work fine in Reaper and VSThost by Hermann Seib. It's probably a routing misconfiguration.
Most hosts don't treat midi outputting VSTs nicely, it usually requires some non-obvious routing.
You can use pizmidi or RS-MET's midiMonitor to check the flow of midi msgs.
Note that Ableton doesn't support the full midi standard (at least v9 didn't), e.g. it puts all msgs on channel 1 (so it's not possible to use multi-timbral VSTis). 
Did you turn "monitor" to "in", btw?
Can you make a screenshot of your routing?

**Comment by discordance** [comment]
I can output midi to another track using this in the Plugin's Info struct:

```
outputs: 0,
inputs: 0,
midi_outputs: 1,
midi_inputs: 1,
```

But yeah Ableton (10) does not drop the plugin at the right spot. Looks like an Ableton limitation:

[JUCE Forum - possible-midi-only-vst-for-use-in-ableton-live](https://forum.juce.com/t/possible-midi-only-vst-for-use-in-ableton-live/2711/5)

**Comment by piedoom** [comment]
Closing unless there are objections!
