### ISSUE TITLE
Is this mantained?

### ISSUE THREAD

**Issue by Dimev** [RustAudio/vst-rs#166]
Because the last commit was on march 17th, and there doesn't seem to be that much activity after that, both issues and prs

**Comment by crsaracco** [comment]
Not super-actively, dev interest waxes and wanes. The crate is *relatively* complete though, and doesn't really need constant changes for it to work in most DAWs.

Do you need one of the PRs to be in the main branch? I can take a look at it if so. Further PRs for an issue are also welcome if you're up for it.

Right now, there's a little bit more activity (albeit not too much more, people are busy with day jobs) on the following projects:
 - [`vst2-sys`](https://github.com/RustAudio/vst2-sys), a lower-level crate for interfacing with the VST2 API spec, which this crate might eventually use one day
 - [`baseplug`](https://github.com/wrl/baseplug), a framework that aims to target multiple different plugin formats at the same time, not just VST2, which also uses `vst2-sys` as its VST2 API interface

Neither I nor the authors will claim that these crates (incl. `vst-rs`) are "production ready" yet, but these other two might be of more interest if you're looking to contribute to a plugin crate.

Finally, I'll plug the [RustAudio discord](https://discord.com/invite/QPdhk2u) (especially the `#vst2` channel) if you're looking to chat with some folks to gauge interest for a new feature/bugfix/other project/etc. or look for quicker turnaround for help.

Closing the issue since this isn't really actionable otherwise.

**Comment by Dimev** [comment]
Ah thanks!

I was wondering because some things changed from 0.2.1 compared to master, but I'm probably better off on the discord if I want to make a vst host
